name: Update Twingate in nixpkgs

on:
  workflow_dispatch:
    inputs:
      client_version:
        description: 'Version of released linux client'
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository nixpkgs repo
      uses: actions/checkout@v3
      with:
        repository: alexprivalov/nixpkgs
        path: nixpkgs
        ref: master
        fetch-depth: 0
        token: ${{ secrets.PTA }}

    # - name: Run tmate
    #   uses: mxschmitt/action-tmate@v2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PTA }}

    - name: Sync fork of nixpkgs repo
      env:
        GITHUB_TOKEN: ${{ secrets.PTA }}
      run: |
        set -x
        cd nixpkgs
        # git remote add -f upstream "https://github.com/NixOS/nixpkgs.git"
        git remote add -f upstream "https://github.com/Twingate/nixpkgs.git"
        git remote -v
        git branch --all
        git config --list
        git checkout master
        git merge --ff-only upstream/master
        git push

    - name: Create and push branch with new *.nix files
      id: step_create_and_push
      run: |
        set -x
        cd nixpkgs
        OLD_VER=$(cat pkgs/applications/networking/twingate/default.nix | grep "version =" | cut -d '=' -f2 | tr -d '\" ;' | cut -d '+' -f1)
        echo "OLD_VER=${OLD_VER}" >> $GITHUB_ENV
        git checkout -b twingate-${{ github.event.inputs.client_version }}
        echo "new client version - ${{ github.event.inputs.client_version }}, old one - ${OLD_VER}"
        mkdir -p pkgs/applications/networking/twingate || true
        wget https://binaries.twingate.com/client/linux/NIX/stable/twingate-default.nix -O pkgs/applications/networking/twingate/default.nix
        wget https://binaries.twingate.com/client/linux/NIX/stable/twingate-module.nix -O nixos/modules/services/networking/twingate.nix

        git config --global user.email "ochupryna@twingate.com"
        git config --global user.name "Oleksandr Chupryna"

        # Commit and push changes
        git add .
        git commit -m "twingate client: ${OLD_VER} -> ${{ github.event.inputs.client_version }}"
        git push origin twingate-${{ github.event.inputs.client_version }}

    - name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.PTA }}
      run: |
        set -x
        # Create pull request
        cd nixpkgs
        sed -i 's/\[ \] x86_64-linux/\[X\] x86_64-linux/g' .github/PULL_REQUEST_TEMPLATE.md
        sed -i 's/\[ \] Fits/\[X\] Fits/g' .github/PULL_REQUEST_TEMPLATE.md
        gh pr create -R twingate/nixpkgs -t "twingate client: ${{ env.OLD_VER }} -> ${{ github.event.inputs.client_version }}" -F .github/PULL_REQUEST_TEMPLATE.md -H alexprivalov:twingate-${{ github.event.inputs.client_version }}
